import Card from './components/Card';
import Block from './components/Chessblock';
import './style.css';

function App(){
    return (
        <div className="App">
            <Card />
            <div className="Chess">
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block />
                <Block /> 
            </div>
        </div>
    );
};


export default App;